### ISSUE TITLE
Error 117404 when downloading poll results.

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/VTP#13]
When EVC is trying to download poll results, everyone is getting 117404 error when trying to download data. It's an 404 HTTP error which means that script is probably doing something wrong when saving results after the poll is done.

**Comment by larsenv** [comment]
This should probably belong in File-Maker.

Anyway, here's a better explanation of why it's not working:

The server has the files laid out like this for poll results: /<country code>/<year>/<day><month>_r.bin. So for example, there's a poll result for 0619_r.bin (that would be today). Let's say there's a poll result for 0617_r.bin as well.

Some of the Wiis are being weird and requesting files like 0618_r.bin. That file doesn't exist, and I don't know why it's trying to request it!

**Comment by AggPro** [comment]
I know this sounds a liiiiiiiiiitle bit idiotic, but maybe those consoles might have the wrong system time. Maybe they are 1 day late or just ahead of the current date. Who knows?


EDIT: Nevermind, it is idiotic.

**Comment by KcrPL** [comment]
We have a time server on our server so it doesn't matter.

**Comment by larsenv** [comment]
I think I should close this issue since I've had a way to fix 117404 for a while now.

**Comment by KcrPL** [comment]
Very well.

**Comment by Jon8RFC** [comment]
I'm having this problem as well, when first opening the channel, and then after posting my prediction.  I'm not sure when it started, because I haven't used the vote channel in about two weeks.

I can email the sniffed packets if that's helpful for diagnosis, but would prefer not to post them publicly.

**Comment by KcrPL** [comment]
The error should disappear in few hours.

**Comment by Jon8RFC** [comment]
Great, thanks for the info!

**Comment by KcrPL** [comment]
You're welcome :P
