### ISSUE TITLE
Getting error 117404

### ISSUE THREAD

**Issue by benjagamess** [RiiConnect24/VTP#15]
So i booted up the Everybody Votes Channel and for some reasons i'm getting Error 117404 which is like a communication problem, is there any clue why this can happen since it took me like 2 weeks to make RiiConnect24 working, it also does a communication error for all of the other channels, it looks like FORE000006 has taken all over my channels lol

**Comment by benjagamess** [comment]
oh nevermind it worked

**Comment by LNLenost** [comment]
> oh nevermind it worked

how did u fix it? i have the same problem. ty!
