### ISSUE TITLE
Grammar Error for French Prediction Label

### ISSUE THREAD

**Issue by benjagamess** [RiiConnect24/VTP#17]
The label for predicting (in french) "Lequel aura le plus de votes" or something like that, "votes" is misspelled as "voix" which means voice in English, yea just a small detail to fix because some French users will kinda be confused.

**Comment by larsenv** [comment]
Are you talking about something in the Everybody Votes Channel itself? If so, that was written by Nintendo.

Please stop making issues here. I don't know how you found this repository, but it's not the right place to ask about this. Consider joining our Discord: https://discord.gg/rc24

**Comment by benjagamess** [comment]
oh, sorry
